### ISSUE TITLE
Publish to JSR

### ISSUE THREAD

**Issue by uki00a** [denodrivers/redis#438]
- [x] migrate deps to npm and jsr (#440)
- [x] add `deno.lock` & run tests with `--frozen-lockfile` in CI (#442)
- [x] run `deno publish --dry-run` in CI (#465)
- [x] automatically publish the package to JSR from CI (#467)
- [ ] Add link to [@db/redis](https://jsr.io/@db/redis)
